# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'swift-with-realm' do
	pod 'RealmSwift' 
end

target 'swift-with-realmTests' do

end

target 'swift-with-realmUITests' do

end

